#!/bin/bash

if [ -f ~/.profile ]; then
  rm ~/.profile
fi

ln -s ~/.files/profile ~/.profile


if [ -f ~/.bashrc ]; then
  rm ~/.bashrc
fi

ln -s ~/.files/bashrc ~/.bashrc


if [ -f ~/.bash_profile ]; then
  rm ~/.bash_profile
fi

ln -s ~/.files/bash_profile ~/.bash_profile


if [ -f ~/.bash_prompt ]; then
  rm ~/.bash_prompt
fi

ln -s ~/.files/bash_prompt ~/.bash_prompt


if [ -f ~/.bash_aliases ]; then
  rm ~/.bash_aliases
fi

ln -s ~/.files/bash_aliases ~/.bash_aliases


if [ -f ~/.bash_exports ]; then
  rm ~/.bash_exports
fi

ln -s ~/.files/bash_exports ~/.bash_exports


if [ -f ~/.bash_path ]; then
  rm ~/.bash_path
fi

ln -s ~/.files/bash_path ~/.bash_path


if [ -f ~/.gitconfig ]; then
  rm ~/.gitconfig
fi

ln -s ~/.files/gitconfig ~/.gitconfig


if [ -f ~/.gitignore_global ]; then
  rm ~/.gitignore_global
fi

ln -s ~/.files/gitignore_global ~/.gitignore_global


if [ -f ~/.gvimrc ]; then
  rm ~/.gvimrc
fi

ln -s ~/.files/gvimrc ~/.gvimrc


if [ -f ~/.bash_aliases_local ]; then
  rm ~/.bash_aliases_local
fi

cp ~/.files/.bash_aliases_local ~/.bash_aliases_local


if [ -f ~/.bash_prompt_local ]; then
  rm ~/.bash_prompt_local
fi

cp ~/.files/.bash_prompt_local ~/.bash_prompt_local
